apiVersion: v1
kind: Pod
metadata:
  name: ejemplo
  labels:
    app: miapp
spec:
  containers:
    - name: miapp
      image: IMAGE
      ports:
        - name: miapp
          containerPort: 8080
          protocol: TCP
      resources:
          requests:
            memory: "250Mi"
            cpu: "30m"
          limits:
            memory: "700Mi"
            cpu: "100m"    
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20