---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      volumes:
      - name: traefik
        configMap:
          name: traefik
      containers:
        - name: traefik
          image: traefik:v2.7
          volumeMounts:
          - name: traefik
            mountPath: "/etc/traefik"
            readOnly: true
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
            - name: admin
              containerPort: 8080
            - name: websecure
              containerPort: 443
      imagePullSecrets:
        - name: image-pull-secret

