apiVersion: v1
kind: Service
metadata:
  name: laravel-mariadb
spec:
  selector:
    app: laravel-mariadb
  ports:
  - name: laravel-mariadb
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: laravel-mariadb
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`laravel.ejemplo.com`)
    kind: Rule
    services:
    - name: laravel-mariadb
      port: 80

